// Generated by CoffeeScript 1.6.3
(function() {
  var $, Api, EventEmitter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  if (window.zooniverse == null) {
    window.zooniverse = {};
  }

  EventEmitter = window.zooniverse.EventEmitter || require('./event-emitter');

  $ = window.jQuery;

  Api = (function(_super) {
    __extends(Api, _super);

    Api.current = null;

    Api.prototype.project = '.';

    Api.prototype.headers = {};

    Api.prototype.proxyFrame = null;

    function Api(_arg) {
      var host, loadTimeout, path, _ref;
      _ref = _arg != null ? _arg : {}, this.project = _ref.project, host = _ref.host, path = _ref.path, loadTimeout = _ref.loadTimeout;
      Api.__super__.constructor.apply(this, arguments);
      this.trigger("ready");
      this.select();
    }

    Api.prototype.get = function(url, args) {
      console.log("url is " + url + " arguments are ", args);
      return $.getJSON(url, args);
    };

    Api.prototype.getJSON = function(url, args) {
      console.log("url is " + url + " args are ", args);
      return $.getJSON(url, args);
    };

    Api.prototype.post = function() {
      console.log("args are ", args);
      return $.post(args[0], args.slice(1));
    };

    Api.prototype.put = function() {
      return this.request.apply(this, ['put'].concat(__slice.call(args)));
    };

    Api.prototype["delete"] = function() {
      return this.request.apply(this, ['delete'].concat(__slice.call(args)));
    };

    Api.prototype.select = function() {
      this.trigger('select');
      return this.constructor.current = this;
    };

    return Api;

  })(EventEmitter);

  window.zooniverse.Api = Api;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Api;
  }

}).call(this);
